# Generated by Django 5.1.7 on 2025-10-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleranalytics',
            name='inventory_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selleranalytics',
            name='top_products',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
