# Generated by Django 5.1.7 on 2025-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dashboard', '0002_alter_selleranalytics_inventory_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleranalytics',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
