# Generated by Django 5.1.7 on 2026-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(db_index=True, max_length=255)),
                ("payment_type", models.CharField(max_length=50)),
                ("gateway", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway"], name="analytics_e_gateway_b61ff5_idx"
                    ),
                    models.Index(
                        fields=["payment_type"], name="analytics_e_payment_e3cd71_idx"
                    ),
                    models.Index(
                        fields=["status"], name="analytics_e_status_431a38_idx"
                    ),
                ],
            },
        ),
    ]
