# Generated by Django 5.1.7 on 2025-11-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('delivery_system', '0001_initial'),
        ('merchant_user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='delivery_system.deliverytenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant_user.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_available'], name='store_produ_organiz_c1f755_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='store_produ_organiz_21efe5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['delivery_tenant', 'is_available'], name='store_produ_deliver_9afc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['delivery_tenant', 'category'], name='store_produ_deliver_9fbcab_idx'),
        ),
    ]
