# Generated by Django 5.1.7 on 2026-03-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Card, bKash, Rocket etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'plan_type': 'organization', 'plan_id': 3, 'boost_product_id': 12}"),
        ),
    ]
