# Generated by Django 5.1.7 on 2026-03-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
