;/*FB_PKG_DELIM*/

__d("AddOnBottomOverride.react",["react","react-compiler-runtime","react-strict-dom"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(12),c,e;b[0]!==a?(e=a.ref,c=babelHelpers.objectWithoutPropertiesLoose(a,["ref"]),b[0]=a,b[1]=c,b[2]=e):(c=b[1],e=b[2]);var f,g;if(b[3]!==c){a=c;f=a.children;g=a.xstyle;a=babelHelpers.objectWithoutPropertiesLoose(a,["children","xstyle"]);b[3]=c;b[4]=f;b[5]=a;b[6]=g}else f=b[4],a=b[5],g=b[6];b[7]!==f||b[8]!==e||b[9]!==a||b[10]!==g?(c=i.jsx(d("react-strict-dom").html.div,babelHelpers["extends"]({},a,{ref:e,style:g,children:f})),b[7]=f,b[8]=e,b[9]=a,b[10]=g,b[11]=c):c=b[11];return c}g["default"]=a}),98);
__d("CometProfilePlusDisclaimer.react",["fbt","CometPopover_DEPRECATED.react","FDSTextPairing.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react");function a(a){var b=d("react-compiler-runtime").c(12),e=a.contents,f=a.footer;a=a.optimizeTooltipContentPadding;var g=a===void 0?!1:a;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(a=h._(/*BTDS*/"Metric definitions popover"),b[0]=a):a=b[0];var i;b[1]===Symbol["for"]("react.memo_cache_sentinel")?(i={className:"x1uaxe40 x1cnzs8 x1xnnf8n xx6bls6 x106a9eq xh8yej3"},b[1]=i):i=b[1];if(b[2]!==e||b[3]!==g){var k;b[5]!==g?(k=function(a,b){return j.jsx(c("FDSTextPairing.react"),{body:j.jsx("div",babelHelpers["extends"]({},{0:{className:"xwxc41k x1y1aw1k"},1:{className:"xjkvuk6 x1iorvi4"}}[!!g<<0],{children:a.definition})),headline:a.name,level:4},b)},b[5]=g,b[6]=k):k=b[6];k=Array.from(e,k);b[2]=e;b[3]=g;b[4]=k}else k=b[4];b[7]!==f?(e=f!=null?j.jsx("div",babelHelpers["extends"]({className:"xx6bls6 x1cnzs8"},{children:j.jsx(c("FDSTextPairing.react"),{level:4,meta:f})})):null,b[7]=f,b[8]=e):e=b[8];b[9]!==k||b[10]!==e?(f=j.jsx(c("CometPopover_DEPRECATED.react"),{"aria-label":a,withArrow:!0,children:j.jsxs("div",babelHelpers["extends"]({},i,{children:[k,e]}))}),b[9]=k,b[10]=e,b[11]=f):f=b[11];return f}g["default"]=a}),226);
__d("FDSAppFacebookReelsFilled24Icon",["cr:14317"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14317")}),98);
__d("FDSAppFacebookReelsFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("155431"),24);b=a;g["default"]=b}),98);
__d("FDSArticleFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("555274"),24);b=a;g["default"]=b}),98);
__d("FDSLikeFilled24Icon",["cr:15203"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15203")}),98);
__d("FDSLikeFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("509924"),24);b=a;g["default"]=b}),98);
__d("FDSPhoneFilled24Icon",["cr:15392"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15392")}),98);
__d("FDSPhoneFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("558162"),24);b=a;g["default"]=b}),98);
__d("FDSPostFilled24Icon",["cr:13847"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13847")}),98);
__d("FDSPostFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("729677"),24);b=a;g["default"]=b}),98);
__d("IntegratedOnboardingCTAType.facebook",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum").Mirrored(["ADD_CONTACT_INFO","ADD_COVER_PHOTO","ADD_PROFILE_PICTURE","CREATE_MORE_REELS","INVITE_FRIENDS_TO_FOLLOW","JOIN_A_GROUP","READ_ARTICLE_ON_HOW_TO_CREATE_HIGH_QUALITY_CREATIVES","RUN_PAGE_LIKE_AD","SHARE_YOUR_FIRST_POST","SHARE_YOUR_FIRST_REEL"]);c=a;f["default"]=c}),66);
__d("ProdashContentVpvFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2143");b=d("FalcoLoggerInternal").create("prodash_content_vpv",a);e=b;g["default"]=e}),98);
__d("ProfileCometCoverPhotoEditDialog.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{}},root:c("JSResourceForInteraction")("ProfileCometCoverPhotoEditDialog.react").__setRef("ProfileCometCoverPhotoEditDialog.entrypoint")};g["default"]=a}),98);
__d("ProfilePlusCometCompletionMeterItemsUtils",["ProfileCometContext","XCometProfileControllerRouteBuilder","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(a){var b=d("react-compiler-runtime").c(3),e=i(c("ProfileCometContext"));e=e.profileID;var f;b[0]!==a||b[1]!==e?(f=c("XCometProfileControllerRouteBuilder").buildURL({id:e,open_field:a,sk:"about_contact_and_basic_info"}),b[0]=a,b[1]=e,b[2]=f):f=b[2];return f}g.useContactAndBasicInfoTabUrl=a}),98);
__d("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24546421258291682"}),null);
__d("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery.graphql",["ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"surface"}],c=[{alias:null,args:null,concreteType:"LWIAPI",kind:"LinkedField",name:"lwi",plural:!1,selections:[{alias:null,args:[{kind:"Variable",name:"surface",variableName:"surface"}],concreteType:"XFBIntegratedOnboarding",kind:"LinkedField",name:"integrated_onboarding_data",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"cta_list",storageKey:null}],storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",selections:c,type:"Query",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",selections:c},params:{id:b("ProfilePlusIntegratedOnboardingAdInterceptDialogQuery_facebookRelayOperation"),metadata:{},name:"ProfilePlusIntegratedOnboardingAdInterceptDialogQuery",operationKind:"query",text:null}}}();e.exports=a}),null);