;/*FB_PKG_DELIM*/

__d("CometGSUALoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({group_id:"",referral_code:"unknown",referral_surface:"unknown",surface:"unknown"});g["default"]=b}),98);
__d("CometGroupReshareComposerDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="10020195878066117"}),null);
__d("CometGroupReshareComposerDialogQuery$Parameters",["CometGroupReshareComposerDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGroupReshareComposerDialogQuery_facebookRelayOperation"),metadata:{},name:"CometGroupReshareComposerDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGroupReshareComposerDialog.entrypoint",["CometGroupReshareComposerDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var c=a.actorID,e=a.id,f=a.prefillText;a=a.url;return{extraProps:{groupID:e,prefillText:f,url:a},queries:{queryReference:{parameters:b("CometGroupReshareComposerDialogQuery$Parameters"),variables:{actorID:c,composerType:"CREATE",feedLocation:"GROUP",id:e,privacySelectorRenderLocation:"COMET_COMPOSER",scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometGroupReshareComposerDialog.react").__setRef("CometGroupReshareComposerDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometEndOfFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="30222088027378461"}),null);
__d("GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24396606243275791"}),null);
__d("GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters",["GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometMembershipQuestionsEntrypointDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometMembershipQuestionsDialog.entrypoint",["GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters"),variables:{group_id:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometMembershipQuestionsEntrypointDialog.react").__setRef("GroupsCometMembershipQuestionsDialog.entrypoint")};b=a;g["default"]=b}),98);
__d("GroupsCometNewMemberGreetingDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="30071343735843538"}),null);
__d("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9809440292457599"}),null);
__d("GroupsCometParticipationQuestionsDialogQuery$Parameters",["GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometParticipationQuestionsDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometParticipationQuestionsDialog.entrypoint",["GroupsCometParticipationQuestionsDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometParticipationQuestionsDialogQuery$Parameters"),variables:{groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometParticipationQuestionsDialog.react").__setRef("GroupsCometParticipationQuestionsDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometParticipationQuestionsDialogFbts_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometParticipationQuestionsDialogFbts_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometParticipationQuestionsDialogFbts",["fbt","GroupsCometParticipationQuestionsDialogFbts_group.graphql"],(function(a,b,c,d,e,f,g,h){"use strict";var i;i!==void 0?i:i=b("GroupsCometParticipationQuestionsDialogFbts_group.graphql");a=h._(/*BTDS*/"Answer questions");c=h._(/*BTDS*/"Participation review");g.participationQuestionsDialogTitle=a;g.participationReviewDialogTitle=c}),226);
__d("mapMap",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=new Map();a.forEach(function(a,d){c.set(d,b(a,d))});return c}f["default"]=a}),66);
__d("useEventsShareToGivenGroupAction",["Actor","EventCometActionContext","EventCometActionLogger","XCometEventPermalinkControllerRouteBuilder","cr:864","emptyFunction","react","react-compiler-runtime","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h;e=h||d("react");var i=e.useContext,j=e.useRef;function a(a){var e=d("react-compiler-runtime").c(22),f=a.eventID,g=a.eventUrl,h=a.groupID,l=a.isViewerAdmin,m=a.mechanism,n=a.prefillText,o=a.surface,p=a.upcomingCount,q=a.actionType,r=a.actionTarget;a=a.onClose;var s=q===void 0?"click":q,t=r===void 0?"share_to_given_group_button":r,u=a===void 0?k:a;q=d("Actor").useActor();r=q[0];if(e[0]!==f||e[1]!==g){a=(g!=null?g:f!=="")?(q=(a=c("XCometEventPermalinkControllerRouteBuilder").buildUri({event_id:f}).setDomain("www.facebook.com"))==null?void 0:a.toString())!=null?q:"":"";e[0]=f;e[1]=g;e[2]=a}else a=e[2];e[3]!==r||e[4]!==h||e[5]!==n||e[6]!==a?(q={actorID:r,id:h,prefillText:n,url:a},e[3]=r,e[4]=h,e[5]=n,e[6]=a,e[7]=q):q=e[7];g=q;r=j(null);n=c("useCometEntryPointDialog")(b("cr:864"),g);var v=n[0],w=i(c("EventCometActionContext"));e[8]!==w||e[9]!==t||e[10]!==s||e[11]!==f||e[12]!==h||e[13]!==l||e[14]!==m||e[15]!==u||e[16]!==v||e[17]!==o||e[18]!==p?(a=function(){c("EventCometActionLogger").log(f,{acontext:w,mechanism:m,surface:o,target:t,type:s},{group_id:h,is_viewer_admin:l,upcoming_count:p}),v({onReturn:c("emptyFunction"),onShareComplete:function(){c("EventCometActionLogger").log(f,{acontext:w,mechanism:m,surface:o,target:t,type:"share"},{group_id:h,is_viewer_admin:l,upcoming_count:p}),u()},onShareFail:c("emptyFunction"),shareScrapeData:"",storyData:null})},e[8]=w,e[9]=t,e[10]=s,e[11]=f,e[12]=h,e[13]=l,e[14]=m,e[15]=u,e[16]=v,e[17]=o,e[18]=p,e[19]=a):a=e[19];q=a;e[20]!==q?(g={onClick:q,triggerRef:r},e[20]=q,e[21]=g):g=e[21];return g}function k(){}g["default"]=a}),98);
__d("useGroupsCometParticipationQuestionsEntryPointDialog",["FDSCardedDialogLoadingStateLegacy.react","GroupsCometMembershipQuestionsDialog.entrypoint","GroupsCometParticipationQuestionsDialog.entrypoint","GroupsCometParticipationQuestionsDialogFbts","react","react-compiler-runtime","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(2),e=a.groupID;a=a.useMQsInForum;a=a===void 0?!1:a;var f;b[0]!==e?(f={groupID:e},b[0]=e,b[1]=f):f=b[1];return c("useCometEntryPointDialog")(a?c("GroupsCometMembershipQuestionsDialog.entrypoint"):c("GroupsCometParticipationQuestionsDialog.entrypoint"),f,void 0,j)}function j(a){return i.jsx(c("FDSCardedDialogLoadingStateLegacy.react"),{onClose:a,title:d("GroupsCometParticipationQuestionsDialogFbts").participationQuestionsDialogTitle,withCloseButton:!0})}j.displayName=j.name+" [from "+f.id+"]";g["default"]=a}),98);