;/*FB_PKG_DELIM*/

__d("FBReelsEntityDialogImplQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9405496729556300"}),null);
__d("FBReelsEntityDialogImplQuery$Parameters",["FBReelsEntityDialogImplQuery_facebookRelayOperation","FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider","FBReels_deprecate_short_form_video_context_gk.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("FBReelsEntityDialogImplQuery_facebookRelayOperation"),metadata:{},name:"FBReelsEntityDialogImplQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReels_deprecate_short_form_video_context_gkrelayprovider:b("FBReels_deprecate_short_form_video_context_gk.relayprovider"),__relay_internal__pv__FBReelsMediaFooter_comet_enable_reels_ads_gkrelayprovider:b("FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider")}}};e.exports=a}),null);
__d("FBReelsMuteContextDefaultValue",[],(function(a,b,c,d,e,f){"use strict";a={isMuted:!1,setMute:function(a){}};f["default"]=a}),66);
__d("FBReelsMuteContext",["FBReelsMuteContextDefaultValue","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(c("FBReelsMuteContextDefaultValue"));g["default"]=b}),98);
__d("useFBReelsProcessRoute",["CometRouteParams","GlobalVideoPortsID","react-compiler-runtime","useRoutePassthroughProps","useSetVideoShareDownstreamSignalTracking","uuidv4"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=d("react-compiler-runtime").c(25),b=d("CometRouteParams").useRouteParams(),e=c("useRoutePassthroughProps")()||{},f=typeof b.video_id==="string"?b.video_id:"",g=typeof b.hide_next==="boolean"?b.hide_next:!1,h=typeof b.page_id==="string"?b.page_id:"",i=typeof e.trackingString==="string"?e.trackingString:"",j=typeof e.rootVideoTrackingKey==="string"?e.rootVideoTrackingKey:"",k=typeof e.rootVideoEncryptedTrackingKey==="string"?e.rootVideoEncryptedTrackingKey:"",l=typeof e.rootVideoClickTrackingLinkshimCb==="string"?e.rootVideoClickTrackingLinkshimCb:"",m=typeof e.rootVideoEncryptedClickTracking==="string"?e.rootVideoEncryptedClickTracking:"",n=typeof e.rootVideoID==="string"?e.rootVideoID:f,o;a[0]!==e.portableVideoID?(o=e.portableVideoID!=null&&typeof e.portableVideoID==="string"?d("GlobalVideoPortsID").ensureVideoID(e.portableVideoID):null,a[0]=e.portableVideoID,a[1]=o):o=a[1];o=o;var p=typeof b.group_id==="string"?b.group_id:null,q="";typeof b.s==="string"?q=b.s:typeof e.s==="string"&&(q=e.s);a[2]!==e.sessionID?(b=typeof e.sessionID==="string"?e.sessionID:c("uuidv4")(),a[2]=e.sessionID,a[3]=b):b=a[3];b=b;var r=!Boolean(e.showComments),s=typeof e.isMuted==="boolean"?e.isMuted:null,t=typeof e.index==="number"?e.index:null,u=e.paginationFragment;e=e.paginationFragmentKey;var v;a[4]!==f?(v=function(a){return f!=null&&f.length>0},a[4]=f,a[5]=v):v=a[5];c("useSetVideoShareDownstreamSignalTracking")(v);a[6]!==t||a[7]!==u||a[8]!==e||a[9]!==p||a[10]!==r||a[11]!==s||a[12]!==g||a[13]!==h||a[14]!==o||a[15]!==l||a[16]!==m||a[17]!==k||a[18]!==n||a[19]!==j||a[20]!==q||a[21]!==i||a[22]!==f||a[23]!==b?(v={aggregationPageNodeIndex:t,aggregationPaginationFragment:u,aggregationPaginationFragmentKey:e,groupID:p,isFullScreen:r,isMutedFromPreviousRoute:s,isNextButtonHidden:g,pageID:h,portableVideoID:o,rootVideoClickTrackingLinkshimCb:l,rootVideoEncryptedClickTracking:m,rootVideoEncryptedTrackingKey:k,rootVideoID:n,rootVideoTrackingKey:j,source:q,trackingString:i,videoID:f,viewerSessionID:b},a[6]=t,a[7]=u,a[8]=e,a[9]=p,a[10]=r,a[11]=s,a[12]=g,a[13]=h,a[14]=o,a[15]=l,a[16]=m,a[17]=k,a[18]=n,a[19]=j,a[20]=q,a[21]=i,a[22]=f,a[23]=b,a[24]=v):v=a[24];return v}g["default"]=a}),98);
__d("useFBReelsMute",["CometRouteRenderType","FBReelsGating","react","react-compiler-runtime","useFBReelsProcessRoute"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useState;function a(){var a=d("react-compiler-runtime").c(3),b=d("CometRouteRenderType").useIsPushView(),e=c("useFBReelsProcessRoute")();e=e.isMutedFromPreviousRoute;var f=d("FBReelsGating").enableUnmuteInDefault();f=f?!b:typeof e==="boolean"?e:!b;e=i(f);b=e[0];var g=e[1];a[0]===Symbol["for"]("react.memo_cache_sentinel")?(f=function(a){g(a)},a[0]=f):f=a[0];e=f;a[1]!==b?(f=[b,e],a[1]=b,a[2]=f):f=a[2];return f}g["default"]=a}),98);
__d("FBReelsMuteContextProvider",["FBReelsMuteContext","FBReelsMuteContextDefaultValue","react","react-compiler-runtime","useFBReelsMute"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useContext;b.useMemo;function k(a){var b=d("react-compiler-runtime").c(6);a=a.children;var e=c("useFBReelsMute")(),f=e[0];e=e[1];var g;b[0]!==f||b[1]!==e?(g={isMuted:f,setMute:e},b[0]=f,b[1]=e,b[2]=g):g=b[2];f=g;e=f;b[3]!==a||b[4]!==e?(g=i.jsx(c("FBReelsMuteContext").Provider,{value:e,children:a}),b[3]=a,b[4]=e,b[5]=g):g=b[5];return g}function a(a){var b=d("react-compiler-runtime").c(5),e=a.children,f=a.shouldUseParentContext,g=j(c("FBReelsMuteContext")),h;b[0]!==e||b[1]!==g||b[2]!==a||b[3]!==f?(h=f===!0&&g!==c("FBReelsMuteContextDefaultValue")?e:i.jsx(k,babelHelpers["extends"]({},a)),b[0]=e,b[1]=g,b[2]=a,b[3]=f,b[4]=h):h=b[4];return h}g["default"]=a}),98);
__d("FDSAppFacebookReelsFilled16Icon",["cr:14315"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14315")}),98);
__d("FDSAppFacebookReelsFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("155427"),16);b=a;g["default"]=b}),98);
__d("FDSAppInstagramFilled12Icon",["cr:14327"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14327")}),98);
__d("FDSAppInstagramFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("547773"),12);b=a;g["default"]=b}),98);
__d("FDSAudioHiFilled20Icon",["cr:13948"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13948")}),98);
__d("FDSAudioHiFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("564390"),20);b=a;g["default"]=b}),98);
__d("FDSAudioOffFilled20Icon",["cr:13952"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13952")}),98);
__d("FDSAudioOffFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("564396"),20);b=a;g["default"]=b}),98);
__d("FDSDots3HorizontalOutline20Icon",["cr:14001"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14001")}),98);
__d("FDSDots3HorizontalOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("484390"),20);b=a;g["default"]=b}),98);
__d("FDSPlayOutline20Icon",["cr:15447"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15447")}),98);
__d("FDSPlayOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("484866"),20);b=a;g["default"]=b}),98);