;/*FB_PKG_DELIM*/

__d("CometFocusTable.react",["CometCompositeFocusIndicator.react","CometFocusTableContext","FocusTable.react","focusScopeQueries","react","react-compiler-runtime","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react"));i.useMemo;b=d("FocusTable.react").createFocusTable(d("focusScopeQueries").focusableScopeQuery);var k=b[0],l=b[1],m=b[2];function n(a){var b=a["aria-label"],c=a.children;a=babelHelpers.objectWithoutPropertiesLoose(a,["aria-label","children"]);return j.jsx(m,babelHelpers["extends"]({},a,{children:j.jsx("div",{"aria-label":b,role:"gridcell",children:c})}))}n.displayName=n.name+" [from "+f.id+"]";var o={horizontal:!0,role:"grid",vertical:!0};function a(a){var b,e=d("react-compiler-runtime").c(14),f,g,i,m;e[0]!==a?(f=a.elementType,g=a.label,m=a.suppressFocusRing,i=babelHelpers.objectWithoutPropertiesLoose(a,["elementType","label","suppressFocusRing"]),e[0]=a,e[1]=f,e[2]=g,e[3]=i,e[4]=m):(f=e[1],g=e[2],i=e[3],m=e[4]);e[5]===Symbol["for"]("react.memo_cache_sentinel")?(a={FocusCell:n,FocusRow:l,FocusTable:k},e[5]=a):a=e[5];a=a;a=a;var p=(b=f)!=null?b:"div";e[6]!==p||e[7]!==g||e[8]!==i?(b=function(a){return j.jsx(p,{"aria-label":g,className:(h||(h=c("stylex")))(a),role:"grid",children:j.jsx(k,babelHelpers["extends"]({},i))})},e[6]=p,e[7]=g,e[8]=i,e[9]=b):b=e[9];e[10]!==f||e[11]!==m||e[12]!==b?(a=j.jsx(c("CometFocusTableContext").Provider,{value:a,children:j.jsx(c("CometCompositeFocusIndicator.react"),{compositeInfo:o,elementType:f,suppressFocusRing:m,children:b})}),e[10]=f,e[11]=m,e[12]=b,e[13]=a):a=e[13];return a}g.CometFocusTable=a;g.CometFocusCell=m;g.CometFocusRow=l}),98);
__d("EmojiFormat.bs",[],(function(a,b,c,d,e,f){"use strict";function g(a){return a.split("_").map(function(a){return parseInt(a,16)})}function a(a){return a.map(function(a){return a.toString(16)}).join("_")}function h(a){return a.map(function(a){return String.fromCodePoint(a)}).join("")}function b(a){return h(g(a))}f.codeStringToCodeArray=g;f.codeArrayToCodeString=a;f.codeArrayToUnicode=h;f.codeStringToUnicode=b}),66);
__d("FDSFriendConfirmFilled20Icon",["cr:14220"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14220")}),98);
__d("FDSFriendConfirmFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("538342"),20);b=a;g["default"]=b}),98);
__d("FDSFriendRemoveFilled20Icon",["cr:15002"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15002")}),98);
__d("FDSFriendRemoveFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("714636"),20);b=a;g["default"]=b}),98);
__d("FDSLocationFilled20Icon",["cr:15234"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15234")}),98);
__d("FDSLocationFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("795388"),20);b=a;g["default"]=b}),98);
__d("FDSPostClockFilled20Icon",["cr:15477"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15477")}),98);
__d("FDSPostClockFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("1604445"),20);b=a;g["default"]=b}),98);
__d("KeyCommandHandler.react",["ReactKeyboardEvent.react","react"],(function(a,b,c,d,e,f,g){var h,i=h||(h=d("react")),j=h.useRef,k=i.unstable_Scope;function a(a){var b=a.children,c=a.onKeyDown;a=a.onKeyUp;var e=j(null);d("ReactKeyboardEvent.react").useKeyboard(e,{onKeyDown:c,onKeyUp:a});return i.jsx(k,{ref:e,children:b})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("LSEmojiSetsType",[],(function(a,b,c,d,e,f){a=Object.freeze({USER_GENERATED:0,RECENTLY_USED:1});f["default"]=a}),66);
__d("MWChatMessengerReactionsUtils",["EmojiFormat.bs","I64","LSEmojiSetsType","LSIntEnum"],(function(a,b,c,d,e,f,g){"use strict";var h,i;b=[{categoryIdx:(h||(h=d("I64"))).of_string("6"),emoji:"\u2764",emojiIdx:h.zero,sortKey:h.zero,type_:(i||(i=d("LSIntEnum"))).ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\ude06",emojiIdx:h.of_string("4"),sortKey:h.one,type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\ude2e",emojiIdx:h.of_string("84"),sortKey:h.of_string("2"),type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\ude22",emojiIdx:h.of_string("48"),sortKey:h.of_string("3"),type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\ude21",emojiIdx:h.of_string("52"),sortKey:h.of_string("4"),type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\udc4d",emojiIdx:h.of_string("131"),sortKey:h.of_string("5"),type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)},{categoryIdx:h.zero,emoji:"\ud83d\udc4e",emojiIdx:h.of_string("132"),sortKey:h.of_string("6"),type_:i.ofNumber(c("LSEmojiSetsType").USER_GENERATED)}];e=b.slice(0,6);var j=d("EmojiFormat.bs").codeArrayToUnicode([10084,65039]),k=d("EmojiFormat.bs").codeArrayToUnicode([10084]);function a(a){if(a===j)return!0;else return a===k}f=6;g.defaultStaticReactions=b;g.defaultCustomizableReactions=e;g.heartType1=j;g.heartType2=k;g.isHeart=a;g.cUSTOM_REACTIONS_NUM=f}),98);
__d("MWChatReactionEmoji",["cr:4707"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:4707")}),98);
__d("MWChatReactionsUtils",["MetaConfig","cr:3890"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=c("MetaConfig")._("58");return new Set(a.split(",").map(function(a){return{codepoints:[a.codePointAt(0)],id:a}}))}g.cUSTOM_REACTIONS_NUM=(d=b("cr:3890")).cUSTOM_REACTIONS_NUM;g.defaultStaticReactions=d.defaultStaticReactions;g.defaultCustomizableReactions=d.defaultCustomizableReactions;g.heartType1=d.heartType1;g.heartType2=d.heartType2;g.isHeart=d.isHeart;g.getHarmfulEmojisForBroadcastChannels=a}),98);
__d("MWMessageTableFocusTable.react",["fbt","CometKeys","FocusTable.react","emptyFunction"],(function(a,b,c,d,e,f,g,h){"use strict";var i="messages_table";a=function(a,b,c){return c.getAttribute("data-scope")===i};b=d("FocusTable.react").createFocusTable(a);f={key:(e=c("CometKeys")).UP};d={key:e.DOWN};var j={key:e.LEFT};e={key:e.RIGHT};c=[{command:f,description:h._(/*BTDS*/"Previous item"),handler:f=c("emptyFunction")},{command:d,description:h._(/*BTDS*/"Next item"),handler:f},{command:j,description:h._(/*BTDS*/"Next item"),handler:f},{command:e,description:h._(/*BTDS*/"Previous item"),handler:f}];g.scopeID=i;g.scopeQuery=a;g.FocusTable=b;g.commandConfigs=c}),226);
__d("MWMessageCellFocusTable.react",["fbt","CometComponentWithKeyCommands.react","CometKeys","FocusTable.react","MWMessageTableFocusTable.react","focusScopeQueries","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react");b=d("FocusTable.react").createFocusTable(d("focusScopeQueries").tabbableScopeQuery);var k={key:c("CometKeys").ESCAPE},l={key:c("CometKeys").ENTER},m={key:c("CometKeys").SPACE},n=h._(/*BTDS*/"Exit focus region"),o=h._(/*BTDS*/"Enter focus region");function a(a){var b=d("react-compiler-runtime").c(9),e=a.children,f=a.onEnter,g=a.onEscape;a=a.onSpace;var h;if(b[0]!==f||b[1]!==g||b[2]!==a){var i=[];g!=null&&i.push({command:k,description:n,handler:g});f!=null&&i.push({command:l,description:o,handler:f});a!=null&&i.push({command:m,description:o,handler:a});h=c("CometComponentWithKeyCommands.react");i=d("MWMessageTableFocusTable.react").commandConfigs.concat(i);b[0]=f;b[1]=g;b[2]=a;b[3]=h;b[4]=i}else h=b[3],i=b[4];b[5]!==h||b[6]!==e||b[7]!==i?(f=j.jsx(h,{commandConfigs:i,xstyle:!1,children:e}),b[5]=h,b[6]=e,b[7]=i,b[8]=f):f=b[8];return f}e=a;g.FocusTable=b;g.keyCommands=e}),226);
__d("Popup",["isTruthy"],(function(a,b,c,d,e,f,g){function a(a,b,d,e){var f=[];c("isTruthy")(b)&&f.push("width="+b);c("isTruthy")(d)&&f.push("height="+d);var g=document.body;if(g!=null&&b!=null&&b!==0&&d!=null&&d!==0){var h="screenX"in window?window.screenX:window.screenLeft,i="screenY"in window?window.screenY:window.screenTop,j="outerWidth"in window?window.outerWidth:g.clientWidth;g="outerHeight"in window?window.outerHeight:g.clientHeight-22;h=Math.floor(h+(j-b)/2);j=Math.floor(i+(g-d)/2.5);f.push("left="+h);f.push("top="+j)}f.push("scrollbars");return window.open(a,e!=null&&e!==""?e:"_blank",f.join(","))}g.open=a}),98);
__d("WebBloksURLUtils",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){b=new RegExp("[?&]"+b.join("(?:=[^&]*)?|[?&]")+"(?:=[^&]*)?","gi");var c=a.indexOf("?")!==-1?"&":"?";a=a.replace(b,"").replace(/&$/,"");return a.indexOf("?")===-1&&a.indexOf("&")!==-1?a.replace("&","?"):a.replace("?&",c)}function b(a){if(/^(fb|https?|intent):\/\//i.test(a))return a;if(/^mailto:/i.test(a))return a;var b=window.location.protocol+"//"+window.location.hostname,c=a;a.charAt(0)==="/"&&(c=a.substr(1));return b+"/"+c}function c(a,b){b===void 0&&(b=!1);var c=window.location.href;b?window.open(a,"_blank"):a===c?window.location.reload():window.location.href=a}function d(a,b){var c=a.split("?")[0];a=a.split("?")[1]||"";a=g(a);a=babelHelpers["extends"]({},a,{},b);b=Object.entries(a).map(function(a){var b=a[0];a=a[1];return typeof a==="string"&&a.length===0?b:encodeURIComponent(b)+"="+encodeURIComponent(a)}).join("&");return c+"?"+b}function g(a){var b={};a&&a.split("&").forEach(function(a){a=a.split("=");var c=a[0];a=a[1];b[decodeURIComponent(c)]=decodeURIComponent(a===void 0?"":a)});return b}f.removeQueryParams=a;f.qualify=b;f.openURL=c;f.addQueryParamsToUrl=d}),66);
__d("WebGraphQLLegacyHelper",["invariant"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){var b=a.controller,c=a.docID,d=a.queryID,e=a.variables;a=a.legacyResponseFormat;c!=d&&(c||d)!=null||h(0,5819,c,d);b=b.getURIBuilder();d?b.setFBID("query_id",d):b.setFBID("doc_id",c);a&&b.setBool("legacy_response_format",!0);e&&b.setString("variables",JSON.stringify(e));return b.getURI()}g.getURI=a}),98);
__d("XCometGroupAdminActivitiesControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/admin_activities/",Object.freeze({with_note:!1,automatic_action:!1}),void 0);b=a;g["default"]=b}),98);