# Generated by Django 5.1.7 on 2026-05-13 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0012_alter_subscriptionplan_plan_type_and_more"),
        (
            "merchant_user",
            "0005_rename_subscription_plan_organization_subscription_plan_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("payment_for", models.CharField(max_length=50)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization-wide Plan"),
                            ("product_boost", "Product Boosting Add-on"),
                            ("plus_membership", "Plus Membership Plan"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("bkash", "bKash")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "gateway_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic data based on payment type",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.organizationsubscription",
                    ),
                ),
                (
                    "plus_membership_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.customersubscription",
                    ),
                ),
                (
                    "product_boost_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.productboostsubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="global_payments.subscriptionpaymenttransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=50)),
                ("gateway", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merchant_user.organization",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="global_payments.subscriptionpaymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=120, unique=True)),
                ("payment_type", models.CharField(max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "line_items",
                    models.JSONField(
                        blank=True, default=list, help_text="Breakdown of invoice items"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="global_payments.subscriptionpaymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionpaymenttransaction",
            index=models.Index(
                fields=["gateway_transaction_id"], name="global_paym_gateway_b8f46f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpaymenttransaction",
            index=models.Index(fields=["status"], name="global_paym_status_ff9eaa_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionpaymenttransaction",
            index=models.Index(
                fields=["created_at"], name="global_paym_created_1bf981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentanalytics",
            index=models.Index(
                fields=["gateway"], name="global_paym_gateway_b7e9c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentanalytics",
            index=models.Index(
                fields=["payment_type"], name="global_paym_payment_0f599f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentanalytics",
            index=models.Index(fields=["status"], name="global_paym_status_936057_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentanalytics",
            index=models.Index(
                fields=["created_at"], name="global_paym_created_c86180_idx"
            ),
        ),
    ]
