# Generated by Django 5.1.7 on 2026-02-24 05:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_user', '0003_organization_last_dashboard_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=50)),
                ('plan_type', models.CharField(choices=[('general', 'General Store Plan'), ('boosting', 'Product Boosting Add-on'), ('custom', 'Custom Plan')], default='general', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Max users per organization')),
                ('max_products', models.PositiveIntegerField(default=100, help_text='Max products in store')),
                ('max_boosted_products', models.PositiveIntegerField(default=0, help_text='Max boosted products (for boosting plans)')),
                ('storage_gb', models.PositiveIntegerField(default=5, help_text='Storage limit in GB')),
                ('features', models.JSONField(default=dict, help_text="JSON of features, e.g., {'analytics': true, 'priority_support': true}")),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['level', 'price'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('expired', 'Expired')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('current_usage', models.JSONField(default=dict, help_text="Track usage like {'products': 50, 'boosted': 2}")),
                ('boosted_products_count', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='merchant_user.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('pdf_url', models.URLField(blank=True, help_text='Generated PDF URL, e.g., via Cloudinary')),
                ('line_items', models.JSONField(default=list, help_text="List of items, e.g., [{'description': 'Basic Plan', 'amount': 19.99}]")),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='merchant_user.organization')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.organizationsubscription')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBoostSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('boost_end_date', models.DateTimeField()),
                ('priority_level', models.PositiveIntegerField(choices=[(1, 'Standard'), (2, 'Premium'), (3, 'VIP')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict, help_text="Extra data for future features, e.g., {'ad_placement': 'top_feed'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_boosts', to='billing.organizationsubscription')),
            ],
            options={
                'ordering': ['-priority_level', '-boost_start_date'],
            },
        ),
    ]
