# Generated by Django 5.1.7 on 2026-02-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('general', 'General Store Plan'), ('organization', 'Organization-wide Plan'), ('boosting', 'Product Boosting Add-on'), ('custom', 'Custom Plan')], default='general', max_length=50),
        ),
    ]
