# Generated by Django 5.1.7 on 2026-03-01 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscriptionplan_plan_type'),
        ('merchant_user', '0005_rename_subscription_plan_organization_subscription_plan_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['plan_level', 'price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='level',
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='is_expiring_soon',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('expired', 'Expired')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'end_date'], name='billing_org_status_9f7ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['is_expiring_soon', 'end_date'], name='billing_org_is_expi_099cb3_idx'),
        ),
    ]
