# Generated by Django 5.1.7 on 2026-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
