# Generated by Django 5.1.7 on 2026-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_organizationsubscription_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
