# Generated by Django 5.1.7 on 2026-03-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_organizationsubscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_subscriptions', to='billing.subscriptionplan'),
        ),
    ]
