# Generated by Django 5.1.7 on 2026-03-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_organizationsubscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], default='basic', max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cancel', 'Cancel'), ('renew', 'Renew')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscriptionplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscriptionplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='billing.organizationsubscription')),
            ],
        ),
    ]
