# Generated by Django 5.1.7 on 2026-03-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_subscriptionplan_plan_level_and_more'),
        ('merchant_user', '0005_rename_subscription_plan_organization_subscription_plan_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationsubscription',
            unique_together={('organization', 'stripe_subscription_id')},
        ),
    ]
