# Generated by Django 5.1.7 on 2026-03-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_organizationsubscription_unique_together'),
        ('merchant_user', '0005_rename_subscription_plan_organization_subscription_plan_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='merchant_user.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.organizationsubscription'),
        ),
    ]
