# Generated by Django 5.1.7 on 2026-03-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_invoice_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='change_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
