# Generated by Django 5.1.7 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_alter_subscriptionplan_plan_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("7_days", "7 Days"),
                    ("15_days", "15 Days"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly (3 Months)"),
                    ("half_yearly", "Half Yearly (6 Months)"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
