# Generated by Django 5.1.7 on 2026-07-22 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_alter_subscriptionplan_billing_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="badge",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="cashback_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="early_access_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="exclusive_deals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="free_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="free_shipping_min_order",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_free_shipping_orders",
            field=models.PositiveIntegerField(
                default=999999,
                help_text="Maximum free shipping orders during this subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_order_limit",
            field=models.PositiveIntegerField(default=0, help_text="0 = Unlimited"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_spending_limit",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="0 = Unlimited", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="priority_customer_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="priority_order_processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="reward_points_multiplier",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="shipping_discount_percent",
            field=models.PositiveSmallIntegerField(default=0, help_text="0-100%"),
        ),
    ]
