# Generated by Django 5.1.7 on 2025-11-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchant_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_tenant_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_tenant_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='merchant_user.organization'),
        ),
    ]
