# Generated by Django 5.1.7 on 2025-12-22 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('business_type', models.CharField(choices=[('retail', 'Retail Store'), ('wholesale', 'Wholesale Business'), ('manufacturer', 'Manufacturer'), ('service', 'Service Provider'), ('dropshipping', 'Dropshipping'), ('other', 'Other')], default='retail', max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('subscription_plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free_trial', max_length=50)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_products', models.PositiveIntegerField(default=100)),
                ('max_storage_gb', models.PositiveIntegerField(default=1)),
                ('max_monthly_orders', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('delivery_integration', models.CharField(choices=[('internal', 'Internal Delivery System'), ('external', 'External Courier Service'), ('both', 'Both Internal & External'), ('none', 'No Delivery')], default='internal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('delivery_manager', 'Delivery Manager'), ('customer_support', 'Customer Support'), ('viewer', 'Viewer')], default='staff', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('can_login_admin', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_users', to='merchant_user.organization')),
            ],
            options={
                'verbose_name': 'Merchant User',
                'verbose_name_plural': 'Merchant Users',
                'ordering': ['-joined_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('domain_type', models.CharField(choices=[('primary', 'Primary Domain'), ('alias', 'Domain Alias'), ('development', 'Development'), ('staging', 'Staging')], default='primary', max_length=20)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=20)),
                ('ssl_certificate', models.TextField(blank=True)),
                ('ssl_private_key', models.TextField(blank=True)),
                ('ssl_expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('a_record', models.CharField(blank=True, max_length=100)),
                ('cname_record', models.CharField(blank=True, max_length=100)),
                ('txt_record', models.CharField(blank=True, max_length=500)),
                ('google_site_verification', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='merchant_user.organization')),
            ],
            options={
                'verbose_name': 'Organization Domain',
                'verbose_name_plural': 'Organization Domains',
                'unique_together': {('tenant', 'domain')},
            },
        ),
    ]
