# Generated by Django 5.1.7 on 2026-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_user', '0002_alter_merchantuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_dashboard_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
