# Generated by Django 5.1.7 on 2026-03-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_user', '0003_organization_last_dashboard_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='current_period_end',
            new_name='subscription_current_period_end',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='current_period_start',
            new_name='subscription_current_period_start',
        ),
    ]
