# Generated by Django 5.1.7 on 2026-03-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_user', '0004_rename_current_period_end_organization_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='subscription_plan',
            new_name='subscription_plan_level',
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='inactive', max_length=50),
        ),
    ]
