# Generated by Django 5.1.7 on 2026-01-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(blank=True, help_text='Maximum Retail Price', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='merchant_user.organization'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='images',
            field=models.URLField(blank=True, help_text='ImageKit hosted product image URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.URLField(blank=True, help_text='ImageKit hosted product image URL', max_length=1000, null=True),
        ),
    ]
