# Generated by Django 5.2.3 on 2026-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('merchant_user', '0003_organization_last_dashboard_activity'),
        ('store', '0002_remove_productgallery_image_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_available', 'price'], name='store_produ_organiz_5a18c7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='store_produ_organiz_21efe5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', '-created_date'], name='store_produ_organiz_a8fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
    ]
