# Generated by Django 5.1.7 on 2026-02-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_url',
            field=models.URLField(default='https://yourdomain.com/product/0', editable=False, help_text="URL to the product page on the merchant's website", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
