# Generated by Django 5.1.7 on 2026-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_store_url_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
