# Generated by Django 5.1.7 on 2026-01-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_alter_coupon_organization'),
        ('merchant_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='merchant_user.organization'),
        ),
    ]
