# Generated by Django 5.1.7 on 2026-02-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0004_dashboardglobalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardGlobalSettings',
        ),
    ]
